services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - ${WEBSOCKET_DATABASE_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${WEBSOCKET_DATABASE_USER}
      POSTGRES_PASSWORD: ${WEBSOCKET_DATABASE_PASSWORD}
      POSTGRES_DB: ${WEBSOCKET_DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  db:
    driver: local
  pgadmin:
    driver: local
